feature: stationary position updates
SignalK/aisreporter pull request #22
Opened 2021-06-10 22:12 UTC by Krillle

Send stationary position updates with last known position when position is not updated from deltas. 

This solves the issue of AIShub account being suspended after not reporting AIS data for 48 hours and being blocked if not sending AIS data for longer times. This happens typically if GPS device (e.g. chart plotter) is switched off while docking or at anchor, or being off even longer for winter break.

2021-06-11 04:49 UTC, tkurki commented
The feature is ok, but I think the naming is off. The point is not that the boat is stationary - it can be stationary and have gps on nd receiving position updates.

Maybe "send periodically latest position when position data is not updated"? `repeatLastPosition` in code.

And add a note to readme about the real world use case: when this setting is the solution.

2021-06-11 13:07 UTC, Krillle commented
Naming is changed to "last know position updates in code and labels. Feature is added to readme. 

Find updated settings screenshot here: https://www.dropbox.com/sh/6pwtvpnhupmcwfh/AAAvrh0V8yNqFA3bF0WQkj-fa

2021-06-13 19:44 UTC, tkurki commented
You can add images to issues and use the resulting markdown for images:

`![image](https://user-images.githubusercontent.com/1049678/121819974-c9f05c00-cc98-11eb-943e-814889a81947.png)`


![image](https://user-images.githubusercontent.com/1049678/121819974-c9f05c00-cc98-11eb-943e-814889a81947.png)

2021-06-13 19:48 UTC, tkurki requested changes

2021-06-13 19:48 UTC, tkurki commented on src/index.ts
> +  let lastPositonTimeout: any
Typo in the name, missing `i`

2021-06-13 19:48 UTC, tkurki commented on src/index.ts
> +                lastPositonTimeout = setInterval(
You are creating an interval per each configured endpoint and then in each interval invocation sending the message to each endpoint. You should do either one or the other, this code sends n * n messages where n is the number of endpoints.

2021-06-16 17:52 UTC, Krillle commented
- Interval now created outside foreach loop
- Screen in Readme updated
- Typo corrected

2021-06-16 20:07 UTC, merged

2021-06-16 20:10 UTC, tkurki commented
Published in @signalk/aisreporter@1.1.0 - thank you!